image: python:latest
pages:
  stage: deploy

  script:
    - pip install mkdocs-material
    - pip install mkdocs-cinder
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  # only:
    # - master

