site_name: OmniLead
nav:
    - Мои диалоги:
       - 'Панель телефонии': 'my_dialogs.md'
       - 'Карточка клиента': 'card_client.md'
    - История диалогов: 
       - 'Фильтр': 'my_dialogs.md'
       - 'Сохраненный фильтр': 'index.md'
    - Панель супервайзера: 'index.md'
    - 'User Guide':
        - 'Writing your docs': 'writing-your-docs.md'
    - Статистика: 'index.md'
    - Настройки: 'index.md'
    - Телефония: 'phonilia.md'
    - Служебное: 'tehno.md'

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition

